update string encryption/decryption
coti-io/coti-sdk-python pull request #10
Opened 2024-08-18 10:45 UTC by smiller-coti

2024-09-26 19:55 UTC, gmesika-coti requested changes

2024-09-26 19:55 UTC, gmesika-coti commented on coti/crypto_utils.py
> +        print(len(key), block_size)
redundent

2024-09-29 06:13 UTC, smiller-coti commented on coti/crypto_utils.py
> +        print(len(key), block_size)
Fixed

2024-10-07 10:21 UTC, gmesika-coti commented
changes merged

2024-10-07 10:21 UTC, closed without merging