adding string support
coti-io/coti-sdk-python pull request #3
Opened 2024-07-09 08:31 UTC by eitanz-coti

adding string support

2024-07-09 14:50 UTC, smiller-coti commented
[https://github.com/coti-io/coti-sdk-python/blob/b9fcbcfdc73a41d67038047853ef0bd4e735bf9f/coti/crypto_utils.py#L73](load_aes_key function): Since we deleted `write_aes_key`, should we consider deleting `load_aes_key`

[https://github.com/coti-io/coti-sdk-python/blob/b9fcbcfdc73a41d67038047853ef0bd4e735bf9f/coti/crypto_utils.py#L124](built_input_text function): I think we should rename this to `build_uint_input_text` to be consistent with the TypeScript SDK

2024-07-09 14:51 UTC, smiller-coti requested changes, later dismissed
Requested changes left in the previous comment

2024-07-15 06:13 UTC, smiller-coti commented on coti/utils.py
> +def print_account_details(web3): ##### OK ######
Is it intentional to leave the `##### OK ######`?

2024-07-15 06:13 UTC, smiller-coti commented on coti/utils.py
> +def transfer_native(web3, recipient_address, private_key, amount_to_transfer_ether, native_gas_units): ##### OK ######
Is it intentional to leave the `##### OK ######`?

2024-07-15 06:14 UTC, smiller-coti reviewed
See previous comments

2024-07-17 20:04 UTC, gmesika-coti approved these changes

2024-07-17 20:04 UTC, closed without merging